bookshop_admin_homepage:
    pattern:  /
    defaults: { _controller: BookshopAdminBundle:Default:index }
bookshop_admin_user_list:
    pattern:  /user
    defaults: { _controller: BookshopAdminBundle:UserAdmin:index }
bookshop_admin_user_enable:
    pattern:  /user/enable/{userID}
    defaults: { _controller: BookshopAdminBundle:UserAdmin:enable }
    requirements:
        _method:  GET
        userID: \d+
bookshop_admin_user_disable:
    pattern:  /user/disbale/{userID}
    defaults: { _controller: BookshopAdminBundle:UserAdmin:disable }
    requirements:
        _method:  GET
        userID: \d+
bookshop_admin_user_new_edit:
    pattern:  /user/edit/{userID}
    defaults: { _controller: BookshopAdminBundle:UserAdmin:edit }

bookshop_admin_user_edit:
    pattern:  /user/edit/{userID}
    defaults: { _controller: BookshopAdminBundle:UserAdmin:edit }
    requirements:
      _method: POST
      
bookshop_admin_product_list:
    pattern:  /product
    defaults: { _controller: BookshopAdminBundle:ProductAdmin:index }
bookshop_admin_product_add:
    pattern:  /product/add
    defaults: { _controller: BookshopAdminBundle:ProductAdmin:add }
bookshop_admin_product_delete:
  pattern:  /product/delete/{id}
  defaults: { _controller: BookshopAdminBundle:ProductAdmin:delete }
bookshop_admin_product_undelete:
  pattern:  /product/undelete/{id}
  defaults: { _controller: BookshopAdminBundle:ProductAdmin:undelete }
bookshop_admin_product_new_edit:
  pattern:  /product/edit/{id}
  defaults: { _controller: BookshopAdminBundle:ProductAdmin:edit }
bookshop_admin_product_edit:
  pattern:  /product/edit/{id}
  defaults: { _controller: BookshopAdminBundle:ProductAdmin:edit }
  requirements:
      _method: POST
      
bookshop_admin_order_list:
  pattern:  /order
  defaults: { _controller: BookshopAdminBundle:OrderAdmin:index }