bookshop_admin_homepage:
    pattern:  /
    defaults: { _controller: BookshopAdminBundle:Default:index }
bookshop_admin_user_list:
    pattern:  /user
    defaults: { _controller: BookshopAdminBundle:UserAdmin:index }
bookshop_admin_user_enable:
    pattern:  /user/enable/{userID}
    defaults: { _controller: BookshopAdminBundle:UserAdmin:enable }
    requirements:
        _method:  GET
        userID: \d+
bookshop_admin_user_disable:
    pattern:  /user/disbale/{userID}
    defaults: { _controller: BookshopAdminBundle:UserAdmin:disable }
    requirements:
        _method:  GET
        userID: \d+
bookshop_admin_user_new_edit:
    pattern:  /user/edit/{userID}
    defaults: { _controller: BookshopAdminBundle:UserAdmin:edit }

bookshop_admin_user_edit:
    pattern:  /user/edit/{userID}
    defaults: { _controller: BookshopAdminBundle:UserAdmin:edit }
    requirements:
      _method: POST