bookshop_bookshop_homepage:
    pattern:  /
    defaults: { _controller: BookshopBookshopBundle:Default:index }
    
category:
  pattern: category/{id}
  defaults: { _controller: BookshopBookshopBundle:Category:category}
  requirements:
        _method:  GET
        id: \d+

product:
  pattern: product/{id}
  defaults: { _controller: BookshopBookshopBundle:Product:product}
  requirements:
        _method:  GET
        id: \d+
search:
  pattern: search/
  defaults: { _controller: BookshopBookshopBundle:Search:search}
  requirements:
    _method: GET

checkout:
  pattern: checkout/billing
  defaults: { _controller: BookshopBookshopBundle:Checkout:billing}
        
        
cart:
  pattern: cart
  defaults: { _controller: BookshopBookshopBundle:Cart:index}

profile:
  pattern: profile/min
  defaults: { _controller: BookshopBookshopBundle:Profile:showMinim}
