bookshop_bookshop_homepage:
    pattern:  /
    defaults: { _controller: BookshopBookshopBundle:Default:index }
category:
  pattern: category/{id}
  defaults: { _controller: BookshopBookshopBundle:Default:category}
  requirements:
        _method:  GET
        id: \d+
        
cart:
  pattern: cart
  defaults: { _controller: BookshopBookshopBundle:Cart:index}

profile:
  pattern: profile/min
  defaults: { _controller: BookshopBookshopBundle:Profile:showMinim}
  
dashboard_index:
  pattern: dashboard/
  defaults: { _controller: BookshopBookshopBundle:Dashboard:index}
dashboard_billing_address_show:
  pattern: dashboard/billingAddress
  defaults: { _controller: BookshopBookshopBundle:Dashboard:billingAddressShow}
  