parameters:
#    bookshop_bookshop.example.class: Bookshop\BookshopBundle\Example

services:
#  link_service.twig.extension:
#    class: Bookshop\BookshopBundle\Twig\Extensions\LinkServiceExtension
#    tags:
#       - { name: twig.extension }
#    bookshop_bookshop.example:
#        class: %bookshop_bookshop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    bookshop_user.registration.form.type:
            class: Bookshop\BookshopBundle\Form\Type\RegistrationFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: bookshop_user_registration }
    bookshop_user.profile.form.type:
            class: Bookshop\BookshopBundle\Form\Type\ProfileFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: bookshop_user_profile }
